apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
  namespace: spring-app
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/springdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
---
apiVersion: v1
kind: Secret
metadata:
  name: spring-secret
  namespace: spring-app
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: spring
  SPRING_DATASOURCE_PASSWORD: spring123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  namespace: spring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app
          image: jihedafli/student-management:alpine   # Jenkins will retag/update
          ports:
            - containerPort: 8089
          envFrom:
            - configMapRef:
                name: spring-config
            - secretRef:
                name: spring-secret
---
apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: spring-app
spec:
  selector:
    app: spring-app
  ports:
    - name: http
      port: 8089
      targetPort: 8089
      nodePort: 30080
  type: NodePort
